routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('customer-details');
});
Route::resource('customer-details', CustomerDetailsController::class)->middleware('auth');
Route::post('language-validation','CustomerDetailsController@languageStore')->name('CustomerDetailsController.languageStore')->middleware('auth');
Route::post('Interest-validation','CustomerDetailsController@InterestStore')->name('CustomerDetailsController.InterestStore')->middleware('auth');
Auth::routes();
//Route::get('/home', 'HomeController@index')->name('home');

resources/views/admin/Partials/Customer/customerDisplay.blade.php
<div class="tab-pane fade show active" id="nav-display-{{$client->id}}" role="tabpanel" aria-labelledby="nav-display-{{$client->id}}-tab">
    <h3 class="display-5">{{$client->name}} {{$client->surname}}</h3>
    <blockquote class="blockquote">
        <p>South African Id: <strong>{{$client->south_african_id}}</strong></p>
        <p>Mobile Number: <strong>{{$client->mobile}}</strong></p>
        <p>Email Address: <strong>{{$client->email}}</strong></p>
        <p>Birth Date: <strong>{{$client->date_of_birth}}</strong></p>
        <p>Language: <strong>{{$client->languageOptions->language}}</strong></p>
        <p>Interests: <strong>
                @foreach(json_decode($clients[0]->interests)->Interests as $interest)
                    {{$interest}},
                @endforeach
            </strong></p>
    </blockquote>
    <button href="" onclick="if(confirm('Do you want to delete this {{$client->name}}?'))event.preventDefault(); document.getElementById('delete-{{$client->id}}').submit();" class="btn btn-outline-danger ">Delete</button>
    <form id="delete-{{$client->id}}" method="post" action="{{route('customer-details.destroy',$client)}}" style="display: none;">
        @csrf
        @method('DELETE')
    </form>
</div>

resources/views/admin/Partials/Customer/customerEdit.blade.php
<div class="tab-pane fade" id="nav-edit-{{$client->id}}" role="tabpanel" aria-labelledby="nav-edit-{{$client->id}}-tab">
    <h3 class="display-5">Edit Details for: {{$client->name}} {{$client->surname}}</h3>
    <blockquote class="blockquote">
        <form action="{{ route('customer-details.update', $client) }}" method="post" enctype="multipart/form-data">
            @csrf
            @method('PUT')
            <p>Name: <strong><s>{{$client->name}}</s> <input type="text" name="name" value="{{$client->name}}" class="form-control"></strong></p>
            <p>Surname: <strong><s>{{$client->surname}}</s> <input type="text" name="surname" value="{{$client->surname}}" class="form-control"></strong></p>
            <p>South African Id: <strong><s>{{$client->south_african_id}}</s> <input type="number" name="south_african_id" value="{{$client->south_african_id}}" class="form-control"></strong></p>
            <p>Mobile Number: <strong><s>{{$client->mobile}}</s> <input type="number" name="mobile" value="{{$client->mobile}}" class="form-control"></strong></p>
            <p>Email Address: <strong><s>{{$client->email}}</s> <input type="email" name="email" value="{{$client->email}}" class="form-control"></strong></p>
            <p>Birth Date: <strong><s>{{$client->date_of_birth}}</s> <input type="date" name="date_of_birth" value="{{$client->date_of_birth}}" class="form-control"></strong></p>
            <p>Language: <strong><s>{{$client->languageOptions->language}}</s> <select class="form-select form-control" name="language_options_id" aria-label="Select One Language">
                        @foreach($languages as $language)
                            <option @if($language->id == $client->language_options_id) selected @endif value="{{$language->id}}">{{$language->language}}</option>
                        @endforeach
                    </select></strong></p>
            <p>Interests: <strong><s>
                        @foreach(json_decode($clients[0]->interests)->Interests as $i)
                            {{$i}},
                        @endforeach</s>
                    <select class="form-control" multiple="multiple" id="interests[]" name="interests[]" aria-label="Select Multiple Interests">
                        @foreach($interests as $interest)
                            <option @if( in_array($interest->interests, json_decode($clients[0]->interests)->Interests)) selected @endif value="{{$interest->interests}}">{{$interest->interests}}</option>
                        @endforeach
                    </select></strong></p>

            <div class="form-group text-center">
                <input type="submit" class="btn btn-outline-success" name="submit" value="Update">
            </div>
        </form>
    </blockquote>
</div>

resources/views/admin/Partials/Customer/customerMain.blade.php
<div class="d-flex align-items-start">
    <div class="nav flex-column nav-tabs me-3" id="v-pills-tab" role="tablist" aria-orientation="vertical">
        @foreach ($clients as $client)
            <button class="nav-link  @if ($loop->first) active @endif " id="v-pills-{{$client->id}}-tab" data-bs-toggle="pill" data-bs-target="#v-pills-{{$client->id}}" type="button" role="tab" aria-controls="v-pills-{{$client->id}}" aria-selected="false">{{$client->name.' '.$client->surname}}</button>
        @endforeach
    </div>
    <div class="tab-content" id="v-pills-tabContent">
        @foreach ($clients as $client)
            <div class="tab-pane fade @if ($loop->first) show active @endif" id="v-pills-{{$client->id}}" role="tabpanel" aria-labelledby="v-pills-{{$client->id}}-tab">
                <nav>
                    <div class="nav nav-tabs" id="nav-tab" role="tablist">
                        <button class="nav-link active" id="nav-display-{{$client->id}}-tab" data-bs-toggle="tab" data-bs-target="#nav-display-{{$client->id}}" type="button" role="tab" aria-controls="nav-display-{{$client->id}}" aria-selected="true">Display</button>
                        <button class="nav-link" id="nav-edit-{{$client->id}}-tab" data-bs-toggle="tab" data-bs-target="#nav-edit-{{$client->id}}" type="button" role="tab" aria-controls="nav-edit-{{$client->id}}" aria-selected="false">Edit</button>
                    </div>
                </nav>
                <div class="tab-content" id="nav-tabContent">
                    @include('admin.Partials.Customer.customerDisplay',['client' => $client])
                    @include('admin.Partials.Customer.customerEdit',['client' => $client])
                </div>
            </div>
        @endforeach
    </div>
</div>